/**
 *
 * This file is auto-generated. Do not edit manually: changes may be erased.
 * Generated by Aqua compiler: https://github.com/fluencelabs/aqua/.
 * If you find any bugs, please write an issue on GitHub: https://github.com/fluencelabs/aqua/issues
 * Aqua version: 0.6.4-SNAPSHOT
 *
 */
import { Fluence, FluencePeer } from '@fluencelabs/fluence';
import {
    CallParams,
    callFunction,
    registerService,
} from '@fluencelabs/fluence/dist/internal/compilerSupport/v2';


// Services

export interface LocalSrvDef {
    inside: (callParams: CallParams<null>) => void | Promise<void>;
}
export function registerLocalSrv(service: LocalSrvDef): void;
export function registerLocalSrv(serviceId: string, service: LocalSrvDef): void;
export function registerLocalSrv(peer: FluencePeer, service: LocalSrvDef): void;
export function registerLocalSrv(peer: FluencePeer, serviceId: string, service: LocalSrvDef): void;
       

export function registerLocalSrv(...args: any) {
    registerService(
        args,
        {
    "defaultServiceId" : "local_srv",
    "functions" : [
        {
            "functionName" : "inside",
            "argDefs" : [
            ],
            "returnType" : {
                "tag" : "void"
            }
        }
    ]
}
    );
}
      
// Functions
 
export type ClosureBigResult = [string, string]
export function closureBig(
    peer1: string,
    peer2: string,
    config?: {ttl?: number}
): Promise<ClosureBigResult>;

export function closureBig(
    peer: FluencePeer,
    peer1: string,
    peer2: string,
    config?: {ttl?: number}
): Promise<ClosureBigResult>;

export function closureBig(...args: any) {

    let script = `
                    (xor
                     (seq
                      (seq
                       (seq
                        (seq
                         (seq
                          (seq
                           (seq
                            (call %init_peer_id% ("getDataSrv" "-relay-") [] -relay-)
                            (call %init_peer_id% ("getDataSrv" "peer1") [] peer1)
                           )
                           (call %init_peer_id% ("getDataSrv" "peer2") [] peer2)
                          )
                          (par
                           (seq
                            (call -relay- ("op" "noop") [])
                            (xor
                             (seq
                              (call peer1 ("op" "identity") ["co on"] p1Id)
                              (call -relay- ("op" "noop") [])
                             )
                             (seq
                              (call -relay- ("op" "noop") [])
                              (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 1])
                             )
                            )
                           )
                           (null)
                          )
                         )
                         (new $p2Id-0
                          (seq
                           (xor
                            (match "in" "in"
                             (xor
                              (seq
                               (call %init_peer_id% ("op" "identity") ["in"] p2)
                               (ap p2 $p2Id-0)
                              )
                              (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 2])
                             )
                            )
                            (seq
                             (call %init_peer_id% ("peer" "identify") [] p2Info)
                             (ap p2Info.$.external_addresses.[0]! $p2Id-0)
                            )
                           )
                           (call %init_peer_id% ("op" "identity") [$p2Id-0.$.[0]!] p2Id-fix)
                          )
                         )
                        )
                        (call -relay- ("op" "noop") [])
                       )
                       (xor
                        (seq
                         (call -relay- ("op" "noop") [])
                         (new $p2Id
                          (seq
                           (xor
                            (match "on" "in"
                             (xor
                              (seq
                               (call %init_peer_id% ("op" "identity") ["on"] p2-0)
                               (ap p2-0 $p2Id)
                              )
                              (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 3])
                             )
                            )
                            (seq
                             (call %init_peer_id% ("peer" "identify") [] p2Info-0)
                             (ap p2Info-0.$.external_addresses.[0]! $p2Id)
                            )
                           )
                           (call %init_peer_id% ("op" "identity") [$p2Id.$.[0]!] p2Id-fix-0)
                          )
                         )
                        )
                        (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 4])
                       )
                      )
                      (xor
                       (call %init_peer_id% ("callbackSrv" "response") [p2Id-fix p2Id-fix-0])
                       (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 5])
                      )
                     )
                     (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 6])
                    )
    `
    return callFunction(
        args,
        {
    "functionName" : "closureBig",
    "returnType" : {
        "tag" : "multiReturn",
        "returnItems" : [
            {
                "tag" : "primitive"
            },
            {
                "tag" : "primitive"
            }
        ]
    },
    "argDefs" : [
        {
            "name" : "peer1",
            "argType" : {
                "tag" : "primitive"
            }
        },
        {
            "name" : "peer2",
            "argType" : {
                "tag" : "primitive"
            }
        }
    ],
    "names" : {
        "relay" : "-relay-",
        "getDataSrv" : "getDataSrv",
        "callbackSrv" : "callbackSrv",
        "responseSrv" : "callbackSrv",
        "responseFnName" : "response",
        "errorHandlingSrv" : "errorHandlingSrv",
        "errorFnName" : "error"
    }
},
        script
    )
}

 

export function closureIn(
    peer1: string,
    config?: {ttl?: number}
): Promise<string>;

export function closureIn(
    peer: FluencePeer,
    peer1: string,
    config?: {ttl?: number}
): Promise<string>;

export function closureIn(...args: any) {

    let script = `
                    (xor
                     (seq
                      (seq
                       (seq
                        (seq
                         (seq
                          (call %init_peer_id% ("getDataSrv" "-relay-") [] -relay-)
                          (call %init_peer_id% ("getDataSrv" "peer1") [] peer1)
                         )
                         (par
                          (seq
                           (call -relay- ("op" "noop") [])
                           (xor
                            (seq
                             (call peer1 ("op" "identity") ["co on"] p1Id)
                             (call -relay- ("op" "noop") [])
                            )
                            (seq
                             (call -relay- ("op" "noop") [])
                             (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 1])
                            )
                           )
                          )
                          (null)
                         )
                        )
                        (xor
                         (match "in" "in"
                          (xor
                           (call %init_peer_id% ("local_srv" "inside") [])
                           (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 2])
                          )
                         )
                         (null)
                        )
                       )
                       (call %init_peer_id% ("op" "identity") ["in"] p2Id)
                      )
                      (xor
                       (call %init_peer_id% ("callbackSrv" "response") [p2Id])
                       (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 3])
                      )
                     )
                     (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 4])
                    )
    `
    return callFunction(
        args,
        {
    "functionName" : "closureIn",
    "returnType" : {
        "tag" : "primitive"
    },
    "argDefs" : [
        {
            "name" : "peer1",
            "argType" : {
                "tag" : "primitive"
            }
        }
    ],
    "names" : {
        "relay" : "-relay-",
        "getDataSrv" : "getDataSrv",
        "callbackSrv" : "callbackSrv",
        "responseSrv" : "callbackSrv",
        "responseFnName" : "response",
        "errorHandlingSrv" : "errorHandlingSrv",
        "errorFnName" : "error"
    }
},
        script
    )
}

 
export type ClosureOut2Result = { air_version: string; external_addresses: string[]; node_version: string; }
export function closureOut2(
    peer2: string,
    config?: {ttl?: number}
): Promise<ClosureOut2Result>;

export function closureOut2(
    peer: FluencePeer,
    peer2: string,
    config?: {ttl?: number}
): Promise<ClosureOut2Result>;

export function closureOut2(...args: any) {

    let script = `
                    (xor
                     (seq
                      (seq
                       (seq
                        (seq
                         (call %init_peer_id% ("getDataSrv" "-relay-") [] -relay-)
                         (call %init_peer_id% ("getDataSrv" "peer2") [] peer2)
                        )
                        (call -relay- ("op" "noop") [])
                       )
                       (xor
                        (seq
                         (seq
                          (xor
                           (match "on" "in"
                            (xor
                             (call peer2 ("local_srv" "inside") [])
                             (seq
                              (seq
                               (call -relay- ("op" "noop") [])
                               (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 1])
                              )
                              (call -relay- ("op" "noop") [])
                             )
                            )
                           )
                           (null)
                          )
                          (call peer2 ("peer" "identify") [] p2Id)
                         )
                         (call -relay- ("op" "noop") [])
                        )
                        (seq
                         (call -relay- ("op" "noop") [])
                         (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 2])
                        )
                       )
                      )
                      (xor
                       (call %init_peer_id% ("callbackSrv" "response") [p2Id])
                       (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 3])
                      )
                     )
                     (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 4])
                    )
    `
    return callFunction(
        args,
        {
    "functionName" : "closureOut2",
    "returnType" : {
        "tag" : "primitive"
    },
    "argDefs" : [
        {
            "name" : "peer2",
            "argType" : {
                "tag" : "primitive"
            }
        }
    ],
    "names" : {
        "relay" : "-relay-",
        "getDataSrv" : "getDataSrv",
        "callbackSrv" : "callbackSrv",
        "responseSrv" : "callbackSrv",
        "responseFnName" : "response",
        "errorHandlingSrv" : "errorHandlingSrv",
        "errorFnName" : "error"
    }
},
        script
    )
}

 
export type ClosureOutResult = { air_version: string; external_addresses: string[]; node_version: string; }
export function closureOut(
    peer2: string,
    config?: {ttl?: number}
): Promise<ClosureOutResult>;

export function closureOut(
    peer: FluencePeer,
    peer2: string,
    config?: {ttl?: number}
): Promise<ClosureOutResult>;

export function closureOut(...args: any) {

    let script = `
                    (xor
                     (seq
                      (seq
                       (seq
                        (seq
                         (seq
                          (seq
                           (seq
                            (call %init_peer_id% ("getDataSrv" "-relay-") [] -relay-)
                            (call %init_peer_id% ("getDataSrv" "peer2") [] peer2)
                           )
                           (call -relay- ("op" "noop") [])
                          )
                          (xor
                           (seq
                            (seq
                             (call -relay- ("op" "noop") [])
                             (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 1])
                            )
                            (call -relay- ("op" "noop") [])
                           )
                           (null)
                          )
                         )
                         (xor
                          (match "on" "in"
                           (xor
                            (call peer2 ("local_srv" "inside") [])
                            (seq
                             (seq
                              (call -relay- ("op" "noop") [])
                              (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 2])
                             )
                             (call -relay- ("op" "noop") [])
                            )
                           )
                          )
                          (null)
                         )
                        )
                        (call peer2 ("peer" "identify") [] p2Id)
                       )
                       (call -relay- ("op" "noop") [])
                      )
                      (xor
                       (call %init_peer_id% ("callbackSrv" "response") [p2Id])
                       (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 3])
                      )
                     )
                     (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 4])
                    )
    `
    return callFunction(
        args,
        {
    "functionName" : "closureOut",
    "returnType" : {
        "tag" : "primitive"
    },
    "argDefs" : [
        {
            "name" : "peer2",
            "argType" : {
                "tag" : "primitive"
            }
        }
    ],
    "names" : {
        "relay" : "-relay-",
        "getDataSrv" : "getDataSrv",
        "callbackSrv" : "callbackSrv",
        "responseSrv" : "callbackSrv",
        "responseFnName" : "response",
        "errorHandlingSrv" : "errorHandlingSrv",
        "errorFnName" : "error"
    }
},
        script
    )
}
