/**
 *
 * This file is auto-generated. Do not edit manually: changes may be erased.
 * Generated by Aqua compiler: https://github.com/fluencelabs/aqua/.
 * If you find any bugs, please write an issue on GitHub: https://github.com/fluencelabs/aqua/issues
 * Aqua version: 0.3.2-SNAPSHOT
 *
 */
import { Fluence, FluencePeer } from '@fluencelabs/fluence';
import { CallParams, callFunction, registerService } from '@fluencelabs/fluence/dist/internal/compilerSupport/v2';

function missingFields(obj: any, fields: string[]): string[] {
    return fields.filter((f) => !(f in obj));
}

// Services

// Functions

export function iterateAndPrint(strings: string[], config?: { ttl?: number }): Promise<void>;
export function iterateAndPrint(peer: FluencePeer, strings: string[], config?: { ttl?: number }): Promise<void>;
export function iterateAndPrint(...args: any) {
    let script = `
                        (xor
                     (seq
                      (seq
                       (call %init_peer_id% ("getDataSrv" "-relay-") [] -relay-)
                       (call %init_peer_id% ("getDataSrv" "strings") [] strings)
                      )
                      (fold strings s
                       (seq
                        (call %init_peer_id% ("println-service-id" "print") [s])
                        (next s)
                       )
                      )
                     )
                     (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 1])
                    )
    `;
    return callFunction(
        args,
        {
            functionName: 'iterateAndPrint',
            returnType: {
                isVoid: true,
                isOptional: false,
            },
            argDefs: [
                {
                    name: 'strings',
                    isOptional: false,
                    callbackDef: null,
                },
            ],
            names: {
                relay: '-relay-',
                getDataSrv: 'getDataSrv',
                callbackSrv: 'callbackSrv',
                responseSrv: 'callbackSrv',
                responseFnName: 'response',
                errorHandlingSrv: 'errorHandlingSrv',
                errorFnName: 'error',
            },
        },
        script,
    );
}

export function iterateAndPrintParallel(
    nodes: string[],
    c: (arg0: { external_addresses: string[] }, callParams: CallParams<'arg0'>) => void,
    config?: { ttl?: number },
): Promise<void>;
export function iterateAndPrintParallel(
    peer: FluencePeer,
    nodes: string[],
    c: (arg0: { external_addresses: string[] }, callParams: CallParams<'arg0'>) => void,
    config?: { ttl?: number },
): Promise<void>;
export function iterateAndPrintParallel(...args: any) {
    let script = `
                        (xor
                     (seq
                      (seq
                       (call %init_peer_id% ("getDataSrv" "-relay-") [] -relay-)
                       (call %init_peer_id% ("getDataSrv" "nodes") [] nodes)
                      )
                      (fold nodes s
                       (par
                        (seq
                         (call -relay- ("op" "noop") [])
                         (xor
                          (seq
                           (seq
                            (call s ("peer" "identify") [] ads)
                            (call -relay- ("op" "noop") [])
                           )
                           (xor
                            (call %init_peer_id% ("callbackSrv" "c") [ads])
                            (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 1])
                           )
                          )
                          (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 2])
                         )
                        )
                        (next s)
                       )
                      )
                     )
                     (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 3])
                    )
    `;
    return callFunction(
        args,
        {
            functionName: 'iterateAndPrintParallel',
            returnType: {
                isVoid: true,
                isOptional: false,
            },
            argDefs: [
                {
                    name: 'nodes',
                    isOptional: false,
                    callbackDef: null,
                },
                {
                    name: 'c',
                    isOptional: false,
                    callbackDef: {
                        argDefs: [
                            {
                                name: 'arg0',
                                isOptional: false,
                                callbackDef: null,
                            },
                        ],
                        returnType: {
                            isVoid: true,
                            isOptional: false,
                        },
                    },
                },
            ],
            names: {
                relay: '-relay-',
                getDataSrv: 'getDataSrv',
                callbackSrv: 'callbackSrv',
                responseSrv: 'callbackSrv',
                responseFnName: 'response',
                errorHandlingSrv: 'errorHandlingSrv',
                errorFnName: 'error',
            },
        },
        script,
    );
}
